### ISSUE TITLE
Hackathon Mispelled

### ISSUE THREAD

**Issue by jaylenw** [MLH/hackcon-website#4]
Hello,

I understand that this repository has the code for Hackcon II.  I was not able to find the repository for Hackcon III website.  On Hackcon III site (http://hackcon.io/) at the bottom left, under MLH, there is a paragraph that contains the word "hackaton".  Just a little mispelled word. 

 I would like to say thanks to you all and I appreciate the work you all do to make MLH exist and running well.

![screenshot from 2015-05-09 23 27 01](https://cloud.githubusercontent.com/assets/6505395/7553263/f530c0da-f6a2-11e4-84f7-a9bc177104c3.png)

**Comment by bih** [comment]
Hey Jaylen!

Huge thanks for sharing this with us. Though this repository is for the [old Hackcon website](http://ii.hackcon.io), we have fixed the typo on the new Hackcon website.

Thanks for being a supporter of MLH!

**Comment by jaylenw** [comment]
Your welcome! No problem.
